### Get all categories
GET http://localhost:8000/api/categories
Authorization: Bearer token

### Get limited categories
GET http://localhost:8000/api/categories?limit=2
Authorization: Bearer token

### Get single category
GET http://localhost:8000/api/categories/1
Authorization: Bearer token

### Create new category
POST http://localhost:8000/api/categories
Content-Type: application/json
Authorization: Bearer token

{
  "name": "Accessories",
  "description": "All kinds of accessories"
}

### Update category
PATCH http://localhost:8000/api/categories/4
Content-Type: application/json
Authorization: Bearer token

{
  "description": "All kinds of desktops"
}

### Delete category
DELETE http://localhost:8000/api/categories/1
Authorization: Bearer token