### Get all products
GET http://localhost:8000/api/products

### Get products by category
GET http://localhost:8000/api/products?categoryId=2

### Get single product
GET http://localhost:8000/api/products/1

### Create product
POST http://localhost:8000/api/products
Content-Type: application/json

{
  "name": "Premium Headphones",
  "categoryId": 2,
  "price": 199.99,
  "stockLeft": 50
}

### Update product
PUT http://localhost:8000/api/products/
Content-Type: application/json

{
  "price": 189.99
}

### Update product on render
https://tech-giant-api.onrender.com/api/products/3
Content-Type: application/json

{
  "price": 189.99
}
### Delete product
DELETE http://localhost:8000/api/products/1

### Add product media
POST http://localhost:8000/api/products/media
Content-Type: application/json

{
  "productId": 2,
  "mediaUrl": "https://example.com/images/headphones.jpg",
  "mediaType": "image"
}

### Remove product media
DELETE http://localhost:8000/api/products/media/1/product/1